services:
  catan-server:
    build:
      context: .
      dockerfile: src/Catan.Server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # postgres:
  #   image: postgres:16
  #   container_name: catan-postgres
  #   environment:
  #     POSTGRES_USER: catan
  #     POSTGRES_PASSWORD: catan
  #     POSTGRES_DB: catan_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
